# infra/k8s/base/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: b2b-rag-api
  labels:
    app: api
    project: b2b-rag
  annotations:
    # IRSA annotation for AWS permissions
    eks.amazonaws.com/role-arn: arn:aws:iam::131292875644:role/github-actions-b2b-rag-staging